version: "3.7"

x-config: &common-config
  RABBITRQ_HOST: rabbitmq
  RABBITRQ_PORT: 5672
  RABBITRQ_USER: guest
  RABBITRQ_PASS: guest
  DATABASE_USER: root
  DATABASE_NAME: GeoNames
  DATABASE_PASS: root
  DATABASE_HOST: db
  DATABASE_PORT: 3306
  LOG_LEVEL: 100

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3300:3306
    volumes:
      - dev-db-chs:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GeoNames

  rabbitmq:
    image: rabbitmq:3.8.4-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672

  cli:
    build:
      context: ../images
      dockerfile: php.Dockerfile
    depends_on:
      - db
      - rabbitmq
    environment:
      <<: *common-config

volumes:
  dev-db-chs:
